### ISSUE TITLE
Request: Support for SSL

### ISSUE THREAD

**Issue by kylemallory** [mitjafelicijan/journalctl-proxy#1]
I'd like to run journalctl-proxy on a publicly accessible server, but would like to harden against malicious users.  One of the first steps would be to provide support for SSL directly, or running through another engine, like Apache, Nginx, or lighttpd that provides the SSL layer.

**Comment by gstrauss** [comment]
You might try using lighttpd [mod_proxy](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModProxy) to proxy back to journalctl-proxy listening on a port on localhost.  Configure TLS with lighttpd listening on port 443, and configure lighttpd to stream HTTP responses with minimal buffering using `server.stream-response-body = 2`

**Comment by mitjafelicijan** [comment]
Adding letsencrypt to the app would be a bit more involved and using something like mod_proxy like @gstrauss recommended is the easiest option. One option is also using nginx and reverse proxy. I will add instructions to readme.
